DUDU/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import app_1.urls as app_1
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app-1/', include(app_1, namespace='app-1')),
    url(r'^$', RedirectView.as_view(permanent=True, url='/app-1/')),
]

app_1/urls.py
from django.conf.urls import url
from .views import index, add_msg

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_msg', add_msg, name='add_msg'),
]

app_1/models.py
from django.db import models

# Create your models here.
class Message(models.Model):
	dari = models.CharField(max_length=27)
	untuk = models.CharField(max_length=27)
	pesan = models.CharField(max_length=40)
	created_date = models.DateTimeField(auto_now_add=True)

app_1/forms.py
from django import forms

class Message_Form(forms.Form):
	error_messages = {
		'required': 'Tolong isi input ini',
	}
	dari_attr = {
		'type': 'text',
		'class': 'form-input',
	}
	untuk_attr = {
		'type': 'text',
		'class': 'form-input',
	}
	pesan_attr = {
		'type': 'text',
		'class': 'form-input',
	}

	dari = forms.CharField(label='Dari :', required=True, max_length=27, widget=forms.TextInput(attrs=dari_attr))
	untuk = forms.CharField(label='Untuk :', required=True, max_length=27, widget=forms.TextInput(attrs=untuk_attr))
	pesan = forms.CharField(label='Pesan :', required=True, max_length=40, widget=forms.TextInput(attrs=pesan_attr))

app_1/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Message_Form
from .models import Message
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
response = {}

def index(request):
	msg_list = Message.objects.all()[::-1]
	response['msg_list'] = msg_list
	response['msg_form'] = Message_Form
	html = 'app_1/index.html'

	page = request.GET.get('page', 1)
	paginator = Paginator(msg_list, 4)

	try:
		msg_list_data = paginator.page(page)
	except PageNotAnInteger:
		msg_list_data = paginator.page(1)
	except EmptyPage:
		msg_list_data = paginator.page(paginator.num_pages)
	response['msg_list_data'] = msg_list_data

	return render(request, html, response)

def add_msg(request):
	form = Message_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['dari'] = request.POST['dari']
		response['untuk'] = request.POST['untuk']
		response['pesan'] = request.POST['pesan']
		msg = Message.objects.create(dari=response['dari'], untuk=response['untuk'], pesan=response['pesan'])
		msg.save()
		html = 'app_1/index.html'
		render(request, html, response)
		return HttpResponseRedirect('/app-1/')
	else:
		return HttpResponseRedirect('/app-1/')

app_1/templates/app_1/index.html
{% extends "app_1/layout/base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
<section class="container-fluid" id="dadu">
	<div class="row">
		<div class="col-md-6 col-sm-12 col-xs-12 text-center" id="left-content">

			<h1>Dari & Untuk</h1>
			<p>Ingin chat si doi tapi gak berani langsung?</p>
			<p>Yuk kirim pesanmu di sini!</p>
			<!-- Trigger/Open the Modal -->
			<button class="btn btn-primary" id="myBtn">Kirim Pesan</button>	
		</div>
		<div class="col-md-6 col-sm-12 col-xs-12" id="right-content">
			{% if msg_list_data %}
				{% for data in msg_list_data %}
					<div class="msg-box">
						<!-- Dari -->
						<div>
							<p><b>Dari :</b> {{ data.dari }}</p>
							<p><b>Untuk :</b> {{ data.untuk }}</p>
							<p><b>Pesan :</b> {{ data.pesan }}</p>
						</div>
					</div>
				{% endfor %}
			{% endif %}
		
			<div id="page-btn">
				{% if msg_list_data.has_other_pages %}
					<ul class="pagination">
						{% if msg_list_data.has_previous %}
							<li><span><a href="{% url 'app-1:index' %}">&laquo;</a></span></li>
						{% else %}
							<li><span>&lsaquo;</span></li>
						{% endif %}

						{% for page_number in msg_list_data.paginator.page_range %}
							{% if msg_list_data.number == page_number %}
								<li class="active"><span>{{ page_number }}</span></li>
							{% else %}
								<li><a href="?page={{ page_number }}">{{ page_number }}</a></li>
							{% endif %}
						{% endfor %}

						{% if msg_list_data.has_next %}
							<li><a href="?page={{ msg_list_data.paginator.num_pages }}">&raquo;</a></li>
						{% else %}
							<li><span>&raquo;</span></li>
						{% endif %}
					</ul>
				{% endif %}
			</div>
		</div>
	</div>

	<!-- The Modal -->
	<div id="myModal" class="modal">
		
		<!-- Modal Content -->
		<div class="modal-content">
			<span class="close">&times;</span>
			<h2>Yuk kirim!</h2>
			<form method="POST" action="{% url 'app-1:add_msg' %}">
				{% csrf_token %}
				{{ msg_form }}
				<button type="submit" class="btn btn-primary" id="kirim-btn">
					KIRIM
				</button>
			</form>
		</div>
	</div>
</section>

{% endblock %}

<!-- Refrensi:
1. www.freepik.com
2. fonts.google.com
3. flatuicolor.com
4. w3schools.com
 -->

app_1/templates/app_1/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Dari & Untuk">
    <meta name="author" content="Rico PP">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/app_1.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <title>
        {% block title %} DUDU Yuk! {% endblock %}
    </title>
</head>

<body>
	<header></header>
	<content>
		{% block content %}
		{% endblock %}
	</content>
	<footer></footer>

	<!-- Jquery n Bootstrap Script -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'js/app_1.js' %}"></script>
</body>
</html>